apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlss-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlss-api
  template:
    metadata:
      labels:
        app: mlss-api
    spec:
    spec:
      containers:
        - name: mlss-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "mlss-api.fullname" . }}-config
            - secretRef:

                name: {{ include "mlss-api.fullname" . }}-secret
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}